controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    methods: [POST]

api_docs:
    path: /docs
    controller: api_platform.action.documentation
