version: "3.9"

services:
  # Symfony / PHP backend
  app:
    build: ./backend
    container_name: forum_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html:cached

      # Persist PHP dependencies installed by Composer so they are not reinstalled on container rebuild
      - backend_vendor:/var/www/html/vendor

      # Persist Symfony cache and logs to avoid regeneration on container restarts
      - backend_var:/var/www/html/var
    depends_on:
      - db
    command: bash -c "php -S 0.0.0.0:8000 -t public"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  # MariaDB
  db:
    image: mariadb:11
    container_name: forum_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: forum_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

  # Vue.js frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: forum_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      - app
    command: npm run dev

volumes:
  db_data:
  backend_vendor:
  backend_var:
